apiVersion: v1
kind: Service
metadata:
  name: whiteboarder-service
  labels:
    app: whiteboarder
spec:
  selector:
    app: whiteboarder
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP

